/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBFS.h"
#include "USBFS_audio.h"
#include "USBFS_cdc.h"
#include "USBFS_hid.h"
#include "USBFS_midi.h"
#include "USBFS_pvt.h"
#include "USBFS_cydmac.h"
#include "USBFS_msc.h"
#include "ADC_CH1.h"
#include "Ch1In_aliases.h"
#include "Ch1In.h"
#include "Ch2In_aliases.h"
#include "Ch2In.h"
#include "DMA_1_dma.h"
#include "DMA_2_dma.h"
#include "Clock_1.h"
#include "isr_1.h"
#include "isr_2.h"
#include "ADC_POT.h"
#include "Pot1_aliases.h"
#include "Pot1.h"
#include "Pot2_aliases.h"
#include "Pot2.h"
#include "Mux.h"
#include "Timer_1.h"
#include "isr_pot.h"
#include "ADC_CH2.h"
#include "USBFS_ep4_dma.h"
#include "USBFS_ep3_dma.h"
#include "USBFS_ep2_dma.h"
#include "USBFS_ep1_dma.h"
#include "USBFS_Dm_aliases.h"
#include "USBFS_Dm.h"
#include "USBFS_Dp_aliases.h"
#include "USBFS_Dp.h"
#include "ADC_CH1_IRQ.h"
#include "ADC_CH1_theACLK.h"
#include "ADC_CH1_Bypass_aliases.h"
#include "ADC_CH1_Bypass.h"
#include "ADC_POT_AMux.h"
#include "ADC_POT_Ext_CP_Clk.h"
#include "ADC_POT_IRQ.h"
#include "ADC_POT_theACLK.h"
#include "ADC_CH2_IRQ.h"
#include "ADC_CH2_theACLK.h"
#include "ADC_CH2_Bypass_aliases.h"
#include "ADC_CH2_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

